### ISSUE TITLE
excessive AI logging on by default [ai_Player1.txt growth]

### ISSUE THREAD

**Issue by c64skin** [forkserf/forkserf#155]
Hey, tried out the new stable release and saw that the ai_Player1.txt file had grown to 1gb afterwards (sadly after a crash)

Seems a tad excessive to me, will you add a limit to this?

**Comment by tlongstretch** [comment]
Ah, yes a ton of information is written to the AI logs at the default loglevel ( 2, or "Info").  I need to change most of the AI Info logging to Debug.

As a work-around, try using the command line flag "-d 3" to log only Warn level messages, which should greatly reduce logging.

**Comment by tlongstretch** [comment]
Hah, probably more importantly it seems the default log level is Debug instead of Info!  I never noticed this, because I have always been specifying some -d #  flag.

I am updating the code to default to Info, and also I am cleaning up the AI log messages so that repetitive messages are not logged at Info levels

**Comment by tlongstretch** [comment]
fixed in unstable, will push to stable soon
