### ISSUE TITLE
deleting the path = settlers disappear

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#286]
settlers disappear

https://user-images.githubusercontent.com/2237225/213583623-3af27a05-2d9a-4e7f-b887-84d0eeadc6fc.mp4

[disapper.zip]

(https://github.com/forkserf/forkserf/files/10461845/disapper.zip)

I think it's because of the water
before this building where people disappear couldn't have the building materials delivered - i had to clear the way to it a couple of times - until i ran it across the desert

**Comment by tlongstretch** [comment]
This is not a bug, it is a result of feature option_LostTransportersClearFaster.  If you turn this off you should see the serfs return to the castle instead of the Knight Hut.  More info here:  https://github.com/forkserf/forkserf/wiki/faster-clearing-of-Lost-serfs

When a serf on a road has the road removed they become Lost.  And if this option is on they may "exit the game" into any friendly building.

**Comment by tlongstretch** [comment]
not a bug
