### ISSUE TITLE
the game shuts down

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#294]
I don't know the reason - but from the very beginning when I follow the project, the game crashes after some time without any error message

exactly in such a way that the game window closes

I have a save here (put it on super speed) in a few moments the game should crash

[12312321.zip](https://github.com/forkserf/forkserf/files/10475414/12312321.zip)

[ai_Player1.txt](https://github.com/forkserf/forkserf/files/10475437/ai_Player1.txt)
[console_out.txt](https://github.com/forkserf/forkserf/files/10475438/console_out.txt)

**Comment by tlongstretch** [comment]
Interesting... it crashes for me also, checking with debugger...

**Comment by zdechlak** [comment]
![image](https://user-images.githubusercontent.com/2237225/213939501-6a6eb893-df6e-4fb2-9f4c-2c75ee6c3991.png)

**Comment by tlongstretch** [comment]
this was due to an array out of bounds issue, the odd thing is it looks like couldn't possibly work, I would have expected to run into crash issues myself  many times but I never saw this trigger.  Is this a very large map size?  I don't think I've ever actually tried size >8 and I rarely play above size 7

The bug was due to using map position as index to array instead of object type, I'm guessing if map is large enough the map pos goes too far out of bounds or something.  Anyway, this is fixed in unstable.  I'll push a new release w/ working Windows realease in next day or two

**Comment by zdechlak** [comment]
I only play on max maps I'm a fanatic

**Comment by tlongstretch** [comment]
ah, okay good (for me)!  you are likely to discover bugs I have not encountered as I haven't tested huge maps myself

**Comment by tlongstretch** [comment]
one thing I have noticed on larger maps is that the AI loops take long enough to complete as the game progresses that playing on high speed results in AI not being able to "keep up" with the state of the game.   However, if you play at normal game speed (ex. 2-4) it should not be a problem.  It is only a problem for me with high-speed debug-testing

**Comment by zdechlak** [comment]
similar bugs were in other projects, they did limit the size of the maps to 8
I hope to play on map 10

**Comment by zdechlak** [comment]
there is also an error on smaller maps - but I don't have a record to send it

**Comment by christian2222** [comment]
I played on ubuntu 24.04, map size 8, no speedup, Forkserf 0.6.3
[console_out.txt](https://github.com/forkserf/forkserf/files/15203969/console_out.txt)
[ai_Player1.txt](https://github.com/forkserf/forkserf/files/15203970/ai_Player1.txt)
[test.zip](https://github.com/forkserf/forkserf/files/15203999/test.zip)
Loading this game crashes with the hint: 
terminate called after throwing an instance of 'ExceptionFreeserf'
  what():  [Unspecified] Failed to draw triangle up (2).
On Linux Mint (VirtualBox) I played the game with speedup and map size 10, but it also crashed by loading a saved game:
Error: [serf.cc] inside Serf::update, serf with excessively high counter detected!  with index 2203 at pos 456669 with type Serf::TypeFarmer and state name PLANNING FARMING has counter 65976 and animation 40
Error: [serf.cc] inside Serf::update, serf with excessively high counter detected!  setting this serf counter to 0
I assume it only crashes because of the Farmer.
